import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import { AccessTokenProvider } from "@/hooks/GlobalContext";

export const metadata = {
  title: "Upload",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AccessTokenProvider>
        <body className={inter.className}>{children}</body>
      </AccessTokenProvider>
    </html>
  );
}
